version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always #总是重启
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    networks:
      - common-network

  mysql-container:
    image: mysql
    volumes:
      - D:\mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: google_login
      MYSQL_ROOT_PASSWORD: xinyu
    networks:
      - common-network

  redis-container:
    image: redis
    volumes:
      - D:\aaa:/data
    networks:
      - common-network

networks:           # 这里的缩进要和 services 同级
  common-network:   # 定义网络
    driver: bridge